### ISSUE TITLE
jieba 分词使用报错

### ISSUE THREAD

**Issue by JackDPro** [vanry/laravel-scout-tntsearch#1]
代码是

```
$tokenizer = new JiebaTokenizer();
$seg_list = $tokenizer->getTokens('哈哈哈哈');
return $seg_list;
```

产生错误信息：

```
Declaration of Vanry\\Scout\\Tokenizers\\Tokenizer::tokenize($text) must be compatible with TeamTNT\\TNTSearch\\Support\\TokenizerInterface::tokenize($text, $stopwords)
```

分词部分是我使用不对吗？如果直接使用「jieba」是正常的。

**Comment by hhxiaohei** [comment]
同问

**Comment by vanry** [comment]
@dongkaipo @hhxiaohei 

由于 `TNTSearch` 分词接口添加了`停用词`: [41a930](https://github.com/teamtnt/tntsearch/commit/41a930cb81ac603cff482af7f7e9eac0f7aca6f9#diff-dcc3ea07217571900a0706dfa2441aae) 导致接口参数不一致。

现已更新分词接口，并且添加建立索引时过滤掉停用词的功能 [8007160](https://github.com/vanry/laravel-scout-tntsearch/commit/80071605ca016e49a81ff46acdbf9afa4c9ab617) 。
