### ISSUE TITLE
lumen5.8能用吗？

### ISSUE THREAD

**Issue by dishcheng** [vanry/laravel-scout-tntsearch#10]
如题

**Comment by dishcheng** [comment]
执行 php artisan scout:import
提示：
In Container.php line 788:
                                    
  Class path.config does not exist

**Comment by dishcheng** [comment]
另外我有多个数据库，执行业务的时候需要操作到不同的数据库，这个轮子能满足吗？

**Comment by vanry** [comment]
lumen 可以用   在容器中注册下 path.config 就可以了
```php
// bootstrap/app.php
$app->instance('path.config', config_path());
```

**Comment by vanry** [comment]
@dishcheng 

lumen 可以用   在容器中注册下 path.config 就可以了
```php
// bootstrap/app.php
$app->instance('path.config', config_path());
```
