### ISSUE TITLE
搜索结果高亮问题

### ISSUE THREAD

**Issue by gary101** [vanry/laravel-scout-tntsearch#13]
请问如果不在视图中使用，如何获得高亮后的匹配结果？

例如API需求，需要返回匹配的高亮结果字符串。

谢谢！

**Comment by vanry** [comment]
@gary101  参考最新的高亮功能 https://github.com/vanry/laravel-scout-tntsearch#%E9%AB%98%E4%BA%AE

**Comment by gary101** [comment]
@vanry 好的感谢！我之前研究源码，使用了以下方式实现高亮（验证ok）：
```
use Vanry\Scout\Highlighter;
use Vanry\Scout\Tokenizers\JiebaTokenizer;

$this->hl = new Highlighter(new JiebaTokenizer);   // 这里指定分词器
 $this->hl->highlight($content, $query);
```
看了您的回复，要更简洁一些，已改为您推荐的方式，谢谢！
