### ISSUE TITLE
采用jieba分词器如何做到分词最小化？

### ISSUE THREAD

**Issue by gary101** [vanry/laravel-scout-tntsearch#14]
中文分词如：软件

默认必须搜索“软件”才可匹配到，

如何做到搜索其中某一个字也可实现匹配？

**Comment by vanry** [comment]
@gary101   默认使用 jieba 的 cutForSearch 已经是最小粒度的分词了

如果实在想按单个汉字分词有2个方法
1. 自定义词库 里面放单个常用汉字
2. 换 scws 分词器 可以设置按汉字分词

**Comment by gary101** [comment]
好的明白，我这边试试看，感谢您的回复！
