### ISSUE TITLE
你好，升级laravel7以后，出现Target class [tntsearch.tokenizer] does not exist.

### ISSUE THREAD

**Issue by shench** [vanry/laravel-scout-tntsearch#15]
你好，升级laravel7以后，出现Target class [tntsearch.tokenizer] does not exist.

**Comment by vanry** [comment]
@shench  你用的哪个版本  目前只有2.0以上才支持 Laravel 7  1.0可能有兼容问题
另外 是不是在使用高亮时 出现的这个错误

**Comment by shench** [comment]
@vanry 是的，我已经解决了这个问题，感谢你的回复！
