### ISSUE TITLE
有办法根据不同字段不同匹配程度排序嘛

### ISSUE THREAD

**Issue by CreationLee** [vanry/laravel-scout-tntsearch#16]
可不可以根据不同字段，比如标题匹配排第一、用户名匹配排第二，匹配程度越高越靠前。
我看了官方文档也没看到

**Comment by vanry** [comment]
@CreationLee  目前只能对搜索结果集按字段升序降序排序 也就是常用的 sql 中的 order by。

你说的不同字段赋予不同权重的功能 tntsearch 引擎目前还不支持，可换用 elasticsearch 和 xunsearch。

**Comment by CreationLee** [comment]
@vanry 好的，谢谢，请问有关于xunsearch好用的第三方包嘛，主要是xunsearch安装太麻烦

**Comment by vanry** [comment]
@CreationLee packagist 上面搜一下  前几名都可以  有官方独立的 hightman/xunsearch，也有 laravel 和 scout 的扩展

**Comment by CreationLee** [comment]
@vanry 好的，谢谢
