### ISSUE TITLE
能否加入min_score的API支持？

### ISSUE THREAD

**Issue by gary101** [vanry/laravel-scout-tntsearch#19]
搜索结果时，为了过滤掉关联度极低的内容，需要使用min_score去过滤。

原生DSL支持min_score参数，但是此库不支持。能否加入？

效果类似：
`Model::search('KEYWORD')->minScore(1.0)`

**Comment by vanry** [comment]
原生DSL支持min_score参数指的是tntsearch还是scout

**Comment by vanry** [comment]
@gary101 原生DSL支持min_score参数指的是tntsearch还是scout
