### ISSUE TITLE
导入数据后,在添加where查询,调用paginate时,total统计数量不对

### ISSUE THREAD

**Issue by YanFengQiLi** [vanry/laravel-scout-tntsearch#20]
tntsearch版本:2.2.0

DjSound::search($word)->where('status',1)->paginate(10);

查询结果确实是1条数据,但是 total 显示为2条

**Comment by vanry** [comment]
@YanFengQiLi  已修复  更新到 2.3.2 即可

**Comment by YanFengQiLi** [comment]
感谢, 我这就更新试一下
