### ISSUE TITLE
Class Vanry\Scout\Tokenizers\JiebaTokenizer contains 1 abstract method and must therefore be declared abstract or implement the remaining methods 

### ISSUE THREAD

**Issue by andyhuang123** [vanry/laravel-scout-tntsearch#21]
php7.4
laravel7.0

local.ERROR: Class Vanry\Scout\Tokenizers\JiebaTokenizer contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (TeamTNT\TNTSearch\Support\TokenizerInterface::getPattern) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 1): Class Vanry\\Scout\\Tokenizers\\JiebaTokenizer contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (TeamTNT\\TNTSearch\\Support\\TokenizerInterface::getPattern) at /www/wwwroot/news.com/vendor/vanry/laravel-scout-tntsearch/src/Tokenizers/JiebaTokenizer.php:8)

类实现（implements）接口时，必须完全实现接口中的所有方法；
类继承（extends）抽象类时，只需对需要用到的抽象方法进行重写。

**Comment by vanry** [comment]
@andyhuang123  已修复  tntsearch 更新了 `TokenizerInterface` 导致的

**Comment by andyhuang123** [comment]
> `TokenizerInterface`

good
