### ISSUE TITLE
创建索引后用分词搜索不到结果

### ISSUE THREAD

**Issue by daniuwo** [vanry/laravel-scout-tntsearch#23]
一行数据：王者荣耀，游戏，小伙
搜索：游戏或小伙能搜到 ，搜索 王者 或者 荣耀 搜不到

看了这里的[教程](https://baijunyao.com/article/154)，照做一遍也不行，搜全文能都到。

请问我是哪里没做对吗
执行 php artisan scout:import "App\Models\Topic"  创建索引，是不是没成功创建分词

**Comment by vanry** [comment]
@daniuwo 这个是 1.0 的教程  现在已经升级到 2.0 了， 可以按照 [https://github.com/vanry/laravel-scout-tntsearch/blob/master/README.md](https://github.com/vanry/laravel-scout-tntsearch/blob/master/README.md) 步骤使用。
