### ISSUE TITLE
Call to undefined method Illuminate\\Database\\Query\\Builder::search()

### ISSUE THREAD

**Issue by SamHz** [vanry/laravel-scout-tntsearch#4]
都装好了，运行分索引了，但提示search()找不到方法

**Comment by vanry** [comment]
@SamHz  在模型中引入 `Searchable Trait`  
参考说明: [用法](https://github.com/vanry/laravel-scout-tntsearch#%E7%94%A8%E6%B3%95)

**Comment by SamHz** [comment]
我是跟着[这里](https://baijunyao.com/article/154) 做的
这个`public $asYouType = true;`是什么意思？能不能说明一下，谢谢
上面那个连接与你发给我的有出入，所以弄不清楚按那个。
`<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Laravel\Scout\Searchable;

class Post extends Model
{
    use Searchable;

    /**
     * Get the indexable data array for the model.
     *
     * @return array
     */
   public function toSearchableArray()
    {
        return $this->only('id', 'title', 'content');
    }
}`

**Comment by vanry** [comment]
`$asYouType` 翻译过来就是 "当你输入时"，也就是我们常说的实时搜索，跟你平时使用搜索引擎一样，每输入一个字都会返回搜索结果。

**Comment by vanry** [comment]
@SamHz
$asYouType 翻译过来就是 "当你输入时"，也就是我们常说的实时搜索，跟你平时使用搜索引擎一样，每输入一个字都会返回搜索结果。

**Comment by SamHz** [comment]
@vanry 那就是说，这个`$asYouType`是必须要有的，对吗？

**Comment by vanry** [comment]
@SamHz   非必须  可以去掉
