### ISSUE TITLE
怎么用orderBy查询语句呢？

### ISSUE THREAD

**Issue by cyhano** [vanry/laravel-scout-tntsearch#7]
怎么用orderBy查询语句呢？

比如：

Article::search("GITHUB")->orderBy("created_at",'desc')->paginate(10);

但是出来的数据不是按 created_at 排序的，好像没有排序

**Comment by cyhano** [comment]
@vanry @baijunyao

**Comment by baijunyao** [comment]
比如说我这样？先获取 id 然后再排序？ https://github.com/baijunyao/laravel-bjyblog/blob/d757756d9370a41e257ce30744dac7dc36d28709/app/Http/Controllers/Home/IndexController.php#L272

**Comment by cyhano** [comment]
> 比如说我这样？先获取 id 然后再排序？ https://github.com/baijunyao/laravel-bjyblog/blob/d757756d9370a41e257ce30744dac7dc36d28709/app/Http/Controllers/Home/IndexController.php#L272

那就不能用它的search方法了
