### ISSUE TITLE
使用另一种修改语句来修改数据，同步索引没能生效

### ISSUE THREAD

**Issue by 000black000** [vanry/laravel-scout-tntsearch#8]
$first = \App\Models\Article::find(1);
$first->content = '一个用PHP编写的功能齐全的全文搜索引擎';
$first->save();

这时候，搜索关键词：‘一个’。   // 能返回正确的数据

而把上面的修改语句换成：
\App\Models\Article::where('id',1)->update(['content' => '什么事没什么']);

这时候，搜索关键词：‘一个’。   //还是出现修改前的记录：‘一个用PHP编写的功能齐全的全文搜索引擎’，并没有出现期望的：空数据

也就是说：
    \App\Models\Article::where('id',1)->update(['content' => '什么事没什么']);
    这种修改语句，同步索引没能生效，为什么呢

**Comment by vanry** [comment]
这个是 `Laravel` 模型事件机制，`App\Models\Article::where('id',1)->update(['content' => '什么事没什么']);` 这一句并没有触发模型的 'updated' 事件

**Comment by vanry** [comment]
@000black000   这个是 `Laravel` 模型事件机制，`App\Models\Article::where('id',1)->update(['content' => '什么事没什么']);` 并没有触发模型的 'updated' 事件
